export const STACK_NAVIGATOR_SCREENS = {
  LOGINSCREEN: 'LoginScreen',
  SIGNUPSCREEN: 'SignUpScreen',
  FORGOTPASSWORDSCREEN: 'ForgotPasswordScreen',
  EMPLOYEEREGISTRATIONSCREEN: 'EmployeeRegistrationScreen',
  MYPETSCREEN: 'MyPetScreen',
  ADDPETSCREEN: 'AddPetScreen',
  PETDETAILSCREEN: 'PetDetailScreen',
  LISTCENTERSCREEN: 'ListCenterScreen',
  PETALBUMSCREEN: 'PetAlbumScreen',
  LISTCHATSCREEN: 'ListChatScreen',
  CHATDETAILSCREEN : 'ChatDetailScreen',
  WORKPROFILESCREEN : 'WorkProfileScreen',
  CREATEJOBSCREEN : 'CreateJobScreen',
  SERVICESCREEN : 'ServiceScreen',
  EDITSERVICESCREEN : 'EditServiceScreen',
  PETCENTERDETAILSCREEN : 'PetCenterDetailScreen',
};
