export const STACK_NAVIGATOR_SCREENS = {
  LOGINSCREEN: 'LoginScreen',
  SIGNUPSCREEN: 'SignUpScreen',
  HOMESCREEN: 'HomeScreen',
  FORGOTPASSWORDSCREEN: 'ForgotPasswordScreen',
  EMPLOYEEREGISTRATIONSCREEN: 'EmployeeRegistrationScreen',
  MYPETSCREEN: 'MyPetScreen',
  ADDPETSCREEN: 'AddPetScreen',
  PETDETAILSCREEN: 'PetDetailScreen',
  EDITPETSCREEN: 'EditPetScreen',
  LISTCENTERSCREEN: 'ListCenterScreen',
  PETALBUMSCREEN: 'PetAlbumScreen',
  LISTCHATSCREEN: 'ListChatScreen',
  CHATDETAILSCREEN : 'ChatDetailScreen',
  WORKPROFILESCREEN : 'WorkProfileScreen',
  CREATEJOBSCREEN : 'CreateJobScreen',
  SERVICESCREEN : 'ServiceScreen',
  EDITSERVICESCREEN : 'EditServiceScreen',
  PETCENTERDETAILSCREEN : 'PetCenterDetailScreen',
  APPOINMENTSCREEN: 'AppointmentScreen',
  MANAGEPETBREEDINGSCREEN: 'ManagePetBreedingScreen',
  PETCENTERSERVICESCREEN: 'PetCenterServiceScreen',
  ADDCENTERBREEDSCREEN: 'AddCenterBreedScreen',
  CENTERBREEDDETAILSCREEN: 'CenterBreedDetailScreen',
  BREEDDETAILSCREEN: 'BreedDetailScreen',
  SCHEDULESCREEN: 'ScheduleScreen',
  MYAPPOINTMENTSCREEN: 'MyAppointmentScreen',
  MYAPPOINTMENTDETAILSCREEN: 'MyAppointmentDetailScreen',
  TRACKINGSCREEN: 'TrackingScreen',
  UPDATETRACKINGSCREEN: 'UpdateTrackingScreen',
  MANAGERSCREEN: 'ManagerScreen',
  EDITPROFILESCREEN: 'EditProfileScreen',
  PAYMENTSCREEN: 'PaymentScreen',
  TRANSACTIONHISTORYSCREEN: 'TransactionHistoryScreen',
  POLICYSCREEN: 'PolicyScreen',
  ABOUTUSSCREEN: 'AboutUsScreen',
  CHECKOUTSCREEN: 'CheckOutScreen',
  REPORTSCREEN: 'ReportScreen',
  APPOINTMENTSTATUSSCREEN: 'AppointmentStatusScreen',
  PLACEFORPETSCREEN: 'PlaceForPetScreen',
  REPORTAPPLICATIONSCREEN: 'ReportApplicationScreen',
  REPORTAPPLICATIONDETAIL: 'ReportApplicationDetail',
  EDITPETALBUM: 'EditPetAlbum',
  MYAPPLICATIONSCREEN: 'MyApplicationScreen',
  EDITOVERVIEWSCREEN: 'EditOverViewScreen',
  REVIEWSCREEN: 'ReviewScreen',
  CHANGEPASSWORDSCREEN: 'ChangePasswordScreen',
  VACCINESCREEN: 'VaccineScreen',
  ADDVACCINESCREEN: 'AddVaccineScreen',
  DISCLAIMERSCREEN: 'DisclaimerScreen',
  EDITPETCENTERSCREEN: 'EditPetCenterScreen',
};
